Update Predator Bot
honteam/Heroes-of-Newerth-Bots pull request #101
Opened 2016-12-21 12:20 UTC by Sparks1992

Added Stone Hide skill usage after using Venomous Leap skill
Added Stone Hide skill usage when retreating

2016-12-21 13:11 UTC, Anakonda requested changes

2016-12-21 13:11 UTC, Anakonda commented on bots/heroes/predator_main.lua
> +						bActionTaken = core.OrderAbility(botBrain, stonehide)
This if is missing end. That is syntax error - do you even test these?

2016-12-21 13:11 UTC, Anakonda commented on bots/heroes/predator_main.lua
> +	return  core.OrderAbility(botBrain, stonehide)
Check if it can be activated, also only cast it if there are enemies

2016-12-21 21:59 UTC, Sparks1992 commented
Changed both issues:
- added the end (sorry, can't test them really well since there is no test+++ button in practice with bots)
- added bCanSee to retreat use of StoneHide

2016-12-22 12:31 UTC, Anakonda commented
open console with ctrl+f8 run command ´showwidget testppp_mainButton´ and close console with ctrl+f8. This should give you the test+++ button.
unitTarget is the hero you last tried to kill it can be anywhere in the map by the time you are retreating - like visible on another lane. You need to use the localunits table, see Moon Queens ult if you need exampl.e

2016-12-22 19:06 UTC, Sparks1992 commented
I updated it, i tried to add Predator in bots folder but i think it's overwritten by the one from the game, because in the bots pick it appears only one Predator, and that's the one from the game.

2016-12-22 20:24 UTC, Sparks1992 commented
done, it works...but it activates too late...first he retreats without using the skill and he starts using it only below 15-20% after i chase him for a couple of seconds. How could i make him use it as soon as he is starting to retreat?

2016-12-22 20:42 UTC, Anakonda commented on bots/heroes/predator_main.lua
> +		if bCanSeeUnit and stonehide:CanActivate() then
instead of bCanSeeunit check that nCount > 0
Then remove all unitTarget stuff

2016-12-22 21:26 UTC, Sparks1992 commented
Updated - removed stuff that wasn't used and added nCount > 0 instead of bCanSee

2016-12-23 17:16 UTC, Anakonda approved these changes
Approved

2017-01-16 21:02 UTC, merged