Emerald Warden Bot
honteam/Heroes-of-Newerth-Bots pull request #99
Opened 2016-11-01 16:38 UTC by Sparks1992

Code for Emerald Warden hero.

2016-11-19 08:15 UTC, Anakonda requested changes

2016-11-19 08:15 UTC, Anakonda commented on EmeraldWarden_main.lua
> +		skills.abilGawain = unitSelf:GetAbility(3)  -- Ultimate -> Summon Gawain
Gawain have 3 abilities that are in slots 5, 6 and 7. You still level up the ability at slot 3.

2016-11-19 08:15 UTC, Anakonda commented on EmeraldWarden_main.lua
> +	local bCanSee = unitTarget and core.CanSeeUnit(botBrain, unitTarget)
unitTarget is nil here. You need to pick target from core.localUnits["EnemyHeroes"]

2016-11-19 10:03 UTC, Sparks1992 commented on EmeraldWarden_main.lua
> +		skills.abilGawain = unitSelf:GetAbility(3)  -- Ultimate -> Summon Gawain
and what should i level up?... gawain has 1 ability at lvl 1, 2 abilities at lvl 2 and 3 at lvl 3

2016-11-19 10:04 UTC, Sparks1992 commented on EmeraldWarden_main.lua
> +	local bCanSee = unitTarget and core.CanSeeUnit(botBrain, unitTarget)
i changed unitTarget to core.localUnits["EnemyHeroes"]

2016-11-19 10:12 UTC, Sparks1992 commented on EmeraldWarden_main.lua
> +		skills.abilGawain = unitSelf:GetAbility(3)  -- Ultimate -> Summon Gawain
should i add skills.abilGawain = unitSelf:GetAbility(5)
skills.abilGawain = unitSelf:GetAbility(6)
skills.abilGawain = unitSelf:GetAbility(7)
and at lvl 6, lvl-up 3-rd, at 11, 5th and at 16 6th?

2016-11-21 08:55 UTC, Anakonda requested changes

2016-11-21 08:55 UTC, Anakonda commented on EmeraldWarden_main.lua
> +	local bCanSee = core.localUnits["EnemyHeroes"] and core.CanSeeUnit(botBrain, unitTarget)
This is list of units. You need to pick one of them and set it to unitTarget. Preferably one that is in range.

2016-11-21 08:55 UTC, Anakonda commented on EmeraldWarden_main.lua
> +		skills.abilGawain = unitSelf:GetAbility(3)  -- Ultimate -> Summon Gawain
```
skills.abilStrike = unitSelf:GetAbility(5)
skills.abilHeal = unitSelf:GetAbility(6)
skills.abilStorm = unitSelf:GetAbility(7)
```
Only add the ones you use later. Also note that as they are passives you cant activate so `:CanActivate()` is always false, use `:GetActualRemainingCooldownTime()` and check if it is 0

2016-11-21 20:51 UTC, Sparks1992 commented on EmeraldWarden_main.lua
> +		skills.abilGawain = unitSelf:GetAbility(3)  -- Ultimate -> Summon Gawain
they're all passive so i don't have to use them... i should only add the threshold for them for increased aggressiveness?

2016-11-21 20:58 UTC, Sparks1992 commented
Please review the changes for skills and threshold

2016-11-21 21:05 UTC, Sparks1992 commented on EmeraldWarden_main.lua
> +	local bCanSee = core.localUnits["EnemyHeroes"] and core.CanSeeUnit(botBrain, unitTarget)
would it be ok if i do it like this?

2017-01-22 12:40 UTC, closed without merging